# Generated by Django 4.2.7 on 2025-11-17 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_depositrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin')], default='ADMIN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_view_dashboard', models.BooleanField(default=True)),
                ('can_control_dice', models.BooleanField(default=False)),
                ('can_view_rounds', models.BooleanField(default=False)),
                ('can_view_bets', models.BooleanField(default=False)),
                ('can_view_wallets', models.BooleanField(default=False)),
                ('can_manage_deposits', models.BooleanField(default=False)),
                ('can_view_transactions', models.BooleanField(default=False)),
                ('can_manage_admins', models.BooleanField(default=False, help_text='Only super admin can manage admins')),
                ('can_view_all_users', models.BooleanField(default=False, help_text='Can view all users or only assigned')),
                ('can_view_all_data', models.BooleanField(default=False, help_text='Can view all data or only filtered')),
                ('created_by', models.ForeignKey(blank=True, help_text='Super admin who created this admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
