# Generated by Django 4.2.26 on 2026-01-19 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_ui_permission'),
        ('accounts', '0004_delete_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payout', models.DecimalField(decimal_places=2, help_text='Total payout amount (100%)', max_digits=10)),
                ('winner_amount', models.DecimalField(decimal_places=2, help_text='Amount paid to winner (90%)', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Commission amount (10%)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payment', to='game.bet')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payments', to='game.gameround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_pe_created_86a4b3_idx'), models.Index(fields=['round'], name='accounts_pe_round_i_680853_idx'), models.Index(fields=['user'], name='accounts_pe_user_id_4b4e4a_idx')],
            },
        ),
    ]
