# Generated by Django 4.2.7 on 2026-01-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userbankdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbankdetail',
            options={'ordering': ['-updated_at', '-is_default', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='qr_code',
        ),
    ]
