# Generated by Django 4.2.7 on 2026-01-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userbankdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
