# Generated by Django 4.2.7 on 2026-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_paymentmethod_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
