# Generated by Django 4.2.7 on 2026-01-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userbankdetail_options'),
        ('accounts', '0012_paymentmethod_account_name_paymentmethod_bank_name'),
    ]

    operations = [
    ]
