# Generated by Django 4.2.7 on 2026-07-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('bet', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('water', models.PositiveSmallIntegerField(default=0)),
                ('earth', models.PositiveSmallIntegerField(default=0)),
                ('fire', models.PositiveSmallIntegerField(default=0)),
                ('busy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
