# Generated by Django 4.2.7 on 2026-07-22 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_number', models.PositiveSmallIntegerField()),
                ('total_stake', models.PositiveIntegerField(default=0)),
                ('total_payout', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='accounts.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UndoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('straight', 'Straight'), ('red', 'Red'), ('black', 'Black'), ('even', 'Even'), ('odd', 'Odd'), ('low', '1-18'), ('high', '19-36'), ('dozen', 'Dozen'), ('column', 'Column')], max_length=16)),
                ('bet_value', models.CharField(blank=True, default='', max_length=8)),
                ('chip', models.PositiveIntegerField()),
                ('visual_chip', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undo_stack', to='accounts.player')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SettledBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('straight', 'Straight'), ('red', 'Red'), ('black', 'Black'), ('even', 'Even'), ('odd', 'Odd'), ('low', '1-18'), ('high', '19-36'), ('dozen', 'Dozen'), ('column', 'Column')], max_length=16)),
                ('bet_value', models.CharField(blank=True, default='', max_length=8)),
                ('amount', models.PositiveIntegerField()),
                ('won', models.BooleanField(default=False)),
                ('payout', models.PositiveIntegerField(default=0)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.round')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PendingBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('straight', 'Straight'), ('red', 'Red'), ('black', 'Black'), ('even', 'Even'), ('odd', 'Odd'), ('low', '1-18'), ('high', '19-36'), ('dozen', 'Dozen'), ('column', 'Column')], max_length=16)),
                ('bet_value', models.CharField(help_text='Number (0-36), dozen/column index (1-3), or empty for even-money bets.', max_length=8)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bets', to='accounts.player')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pendingbet',
            constraint=models.UniqueConstraint(fields=('player', 'bet_type', 'bet_value'), name='uniq_pending_bet_key'),
        ),
    ]
