# Generated by Django 5.1.15 on 2026-08-11 18:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('segment_id', models.CharField(max_length=16)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_angle', models.FloatField(help_text='Absolute wheel angle (deg) under the pointer')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
