/**
 * Casino Games list — all tiles link to web games (APK WebView + browser).
 *
 * Flow (no APK update for new games):
 * 1. App Play → loads website /casino/ once
 * 2. Tap a tile → AndroidBridge.openGame(id, fullUrl) opens that game path
 * 3. Never reload casino when opening a game from the lobby
 *
 * To add a game:
 * 1. Put the tile image in ./images/
 * 2. Append { id, title, image, path } below
 * 3. Redeploy casino (+ host the game under path)
 */
export const GAMES = [
  {
    id: "gundu-ata",
    title: "Gundu Ata",
    image: "images/gundu-ata.jpeg?v=8",
    path: "/game/?v=47&from=casino",
  },
  {
    id: "horse-racing",
    title: "Horse Race",
    image: "images/horse-racing.jpeg?v=8",
    path: "/horse-racing/",
  },
  {
    id: "stock-market",
    title: "Stock Market",
    image: "images/stock-market.jpeg?v=8",
    path: "/trading/",
  },
  {
    id: "live-roulette",
    title: "Live Roulette",
    image: "images/auto-roulette.jpeg?v=8",
    path: "/roulette/",
  },
  {
    id: "chicken-road",
    title: "Chicken Road",
    image: "images/chicken-road.jpeg?v=8",
    path: "/chicken-road/",
  },
  {
    id: "chicken-road-2",
    title: "Chicken Road 2",
    image: "images/chicken-road-2.jpeg?v=8",
    path: "/chicken-road-2/",
  },
  {
    id: "vortex",
    title: "Vortex",
    image: "images/vortex.jpeg?v=8",
    path: "/vortex/",
  },
  {
    id: "vortex-1",
    title: "Vortex 1",
    image: "images/vortex-1.jpeg?v=8",
    path: "/vortex-1/",
  },
  {
    id: "vip-vortex",
    title: "VIP Vortex",
    image: "images/vip-vortex.jpeg?v=8",
    path: "/vip-vortex/",
  },
  {
    id: "plinko",
    title: "Plinko",
    image: "images/plinko.jpeg?v=8",
    path: "/plinko/",
  },
  {
    id: "slide",
    title: "Pin Stop",
    image: "images/slide.jpeg?v=8",
    path: "/slide/",
  },
  {
    id: "chit-pat",
    title: "Chit Pat",
    image: "images/chit-pat.jpeg?v=8",
    path: "/chit-pat/",
  },
  {
    id: "rangu",
    title: "Rangu",
    image: "images/rangu.jpeg?v=8",
    path: "/rangu/",
  },
  {
    id: "mines",
    title: "Mines",
    image: "images/mines.jpeg?v=8",
    path: "/mines/",
  },
  {
    id: "steps",
    title: "Sky Path",
    image: "images/steps.jpeg?v=8",
    path: "/steps/",
  },
  {
    id: "boxes",
    title: "Pick 4",
    image: "images/boxes.jpeg?v=8",
    path: "/boxes/",
  },
  {
    id: "snake",
    title: "Roll & Land",
    image: "images/snake.jpeg?v=8",
    path: "/snake/",
  },
  {
    id: "cases",
    title: "Vault",
    image: "images/cases.jpeg?v=8",
    path: "/cases/",
  },
  {
    id: "air-balloon",
    title: "Air Balloon",
    image: "images/air-balloon.jpeg?v=8",
    path: "/air-balloon/",
  },
  {
    id: "circle-game",
    title: "Circle Bet",
    image: "images/circle-game.jpeg?v=8",
    path: "/circle-game/",
  },
  {
    id: "stop-bar",
    title: "Stop Bar",
    image: "images/stop-bar.jpeg?v=8",
    path: "/stop-bar/",
  },
  {
    id: "spin-dial",
    title: "Spin Dial",
    image: "images/spin-dial.jpeg?v=8",
    path: "/spin-dial/",
  },
  {
    id: "mines-path",
    title: "Mines Path",
    image: "images/mines-path.jpeg?v=8",
    path: "/mines-path/",
  },
  {
    id: "dice-over-under",
    title: "Dice Over Under",
    image: "images/dice-over-under.jpeg?v=8",
    path: "/dice-over-under/",
  },
  {
    id: "color-match",
    title: "Color Match",
    image: "images/color-match.jpeg?v=8",
    path: "/color-match/",
  },
  {
    id: "wheel-pockets",
    title: "Wheel Pockets",
    image: "images/wheel-pockets.jpeg?v=8",
    path: "/wheel-pockets/",
  },
  {
    id: "wave-surf",
    title: "Wave Surf",
    image: "images/wave-surf.jpeg?v=8",
    path: "/wave-surf/",
  },
  {
    id: "keno-pick",
    title: "Keno Pick",
    image: "images/keno-pick.jpeg?v=8",
    path: "/keno-pick/",
  },
  {
    id: "hi-lo-cards",
    title: "Hi-Lo Cards",
    image: "images/hi-lo-cards.jpeg?v=8",
    path: "/hi-lo-cards/",
  },
  {
    id: "aviator",
    title: "Aviator",
    image: "images/aviator.jpeg?v=8",
    path: "/aviator/",
  },
  {
    id: "jet",
    title: "Jet",
    image: "images/jet.jpeg?v=8",
    path: "/jet/",
  },
  {
    id: "maestro",
    title: "Maestro",
    image: "images/maestro.jpeg?v=8",
    path: "/maestro/",
  },
  {
    id: "deep-dive",
    title: "Deep Dive",
    image: "images/deep-dive.jpeg?v=8",
    path: "/deep-dive/",
  },
  {
    id: "sky-lift",
    title: "Sky Lift",
    image: "images/sky-lift.jpeg?v=8",
    path: "/sky-lift/",
  },
  {
    id: "paper-plane",
    title: "Paper Plane",
    image: "images/paper-plane.jpeg?v=8",
    path: "/paper-plane/",
  },
  {
    id: "ufo-lift",
    title: "UFO Lift",
    image: "images/ufo-lift.jpeg?v=8",
    path: "/ufo-lift/",
  },
  {
    id: "shark-bite",
    title: "Shark Bite",
    image: "images/shark-bite.jpeg?v=8",
    path: "/shark-bite/",
  },
  {
    id: "under-6",
    title: "Under 6",
    image: "images/under-6.jpeg?v=8",
    path: "/under-6/",
  },
  {
    id: "rushbet",
    title: "Rush Bet",
    image: "images/rushbet.jpeg?v=8",
    path: "/rushbet/",
  },
  {
    id: "knock6",
    title: "Knock 6",
    image: "images/knock6.jpeg?v=8",
    path: "/knock6/",
  },
  {
    id: "tripleedge",
    title: "Triple Edge",
    image: "images/tripleedge.jpeg?v=8",
    path: "/tripleedge/",
  },
  {
    id: "mirror",
    title: "Mirror",
    image: "images/mirror.jpeg?v=8",
    path: "/mirror/",
  },
  {
    id: "goldlane",
    title: "Gold Lane",
    image: "images/goldlane.jpeg?v=8",
    path: "/goldlane/",
  },
  {
    id: "dead7",
    title: "Dead 7",
    image: "images/dead7.jpeg?v=8",
    path: "/dead7/",
  },
  {
    id: "teenpatti",
    title: "Teen Patti",
    image: "images/teenpatti.jpeg?v=8",
    path: "/teenpatti/",
  },
  {
    id: "pharaohs-fortune",
    title: "Pharaoh's Fortune",
    image: "images/pharaohs-fortune.jpeg?v=8",
    path: "/slots/pharaohs-fortune/",
  },
  {
    id: "atlantis-depths",
    title: "Atlantis Depths",
    image: "images/atlantis-depths.jpeg?v=8",
    path: "/slots/atlantis-depths/",
  },
  {
    id: "thunder-of-asgard",
    title: "Thunder of Asgard",
    image: "images/thunder-of-asgard.jpeg?v=8",
    path: "/slots/thunder-of-asgard/",
  },
  {
    id: "neon-reels-2088",
    title: "Neon Reels 2088",
    image: "images/neon-reels-2088.jpeg?v=8",
    path: "/slots/neon-reels-2088/",
  },
  {
    id: "gold-rush-saloon",
    title: "Gold Rush Saloon",
    image: "images/gold-rush-saloon.jpeg?v=8",
    path: "/slots/gold-rush-saloon/",
  },
  {
    id: "midnight-manor",
    title: "Midnight Manor",
    image: "images/midnight-manor.jpeg?v=8",
    path: "/slots/midnight-manor/",
  },
  {
    id: "dragon-sakura",
    title: "Dragon Sakura",
    image: "images/dragon-sakura.jpeg?v=8",
    path: "/slots/dragon-sakura/",
  },
  {
    id: "cosmic-jackpot",
    title: "Cosmic Jackpot",
    image: "images/cosmic-jackpot.jpeg?v=8",
    path: "/slots/cosmic-jackpot/",
  },
  {
    id: "clockwork-fortune",
    title: "Clockwork Fortune",
    image: "images/clockwork-fortune.jpeg?v=8",
    path: "/slots/clockwork-fortune/",
  },
  {
    id: "jackpot-plunder",
    title: "Jackpot Plunder",
    image: "images/jackpot-plunder.jpeg?v=8",
    path: "/slots/jackpot-plunder/",
  },
  {
    id: "sugar-rush-spins",
    title: "Sugar Rush Spins",
    image: "images/sugar-rush-spins.jpeg?v=8",
    path: "/slots/sugar-rush-spins/",
  },
  {
    id: "temple-of-the-jaguar",
    title: "Temple of the Jaguar",
    image: "images/temple-of-the-jaguar.jpeg?v=8",
    path: "/slots/temple-of-the-jaguar/",
  },
  {
    id: "big-top-bonanza",
    title: "Big Top Bonanza",
    image: "images/big-top-bonanza.jpeg?v=8",
    path: "/slots/big-top-bonanza/",
  },
  {
    id: "frozen-crown",
    title: "Frozen Crown",
    image: "images/frozen-crown.jpeg?v=8",
    path: "/slots/frozen-crown/",
  },
  {
    id: "inferno-peak",
    title: "Inferno Peak",
    image: "images/inferno-peak.jpeg?v=8",
    path: "/slots/inferno-peak/",
  },
  {
    id: "leprechauns-gold",
    title: "Leprechaun's Gold",
    image: "images/leprechauns-gold.jpeg?v=8",
    path: "/slots/leprechauns-gold/",
  },
  {
    id: "olympian-glory",
    title: "Olympian Glory",
    image: "images/olympian-glory.jpeg?v=8",
    path: "/slots/olympian-glory/",
  },
  {
    id: "safari-fortune",
    title: "Safari Fortune",
    image: "images/safari-fortune.jpeg?v=8",
    path: "/slots/safari-fortune/",
  },
  {
    id: "sultans-treasure",
    title: "Sultan's Treasure",
    image: "images/sultans-treasure.jpeg?v=8",
    path: "/slots/sultans-treasure/",
  },
  {
    id: "vegas-royale",
    title: "Vegas Royale 777",
    image: "images/vegas-royale.jpeg?v=8",
    path: "/slots/vegas-royale/",
  },
];
