# Generated by Django 6.1 on 2026-08-10 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('silk_color', models.CharField(help_text='Hex color for silks, e.g. #c62828', max_length=7)),
                ('cloth_color', models.CharField(max_length=7)),
                ('coat_color', models.CharField(max_length=7)),
                ('mane_color', models.CharField(max_length=7)),
                ('fur_map', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parade', 'Parade'), ('ready', 'Ready'), ('racing', 'Racing'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('total_laps', models.PositiveSmallIntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='race.horse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.PositiveSmallIntegerField()),
                ('finish_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('finish_time_seconds', models.FloatField(blank=True, null=True)),
                ('laps_completed', models.PositiveSmallIntegerField(default=0)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='race.horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='race.race')),
            ],
            options={
                'ordering': ['lane'],
                'unique_together': {('race', 'horse'), ('race', 'lane')},
            },
        ),
    ]
