# Generated by Django 6.1 on 2026-08-09 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bankroll', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_side', models.CharField(choices=[('under', 'Under'), ('six', 'Six'), ('over', 'Over')], max_length=8)),
                ('chip', models.PositiveIntegerField()),
                ('card1_label', models.CharField(max_length=2)),
                ('card1_value', models.PositiveSmallIntegerField()),
                ('card1_symbol', models.CharField(max_length=2)),
                ('card1_red', models.BooleanField(default=False)),
                ('card2_label', models.CharField(max_length=2)),
                ('card2_value', models.PositiveSmallIntegerField()),
                ('card2_symbol', models.CharField(max_length=2)),
                ('card2_red', models.BooleanField(default=False)),
                ('sum_value', models.PositiveSmallIntegerField()),
                ('result_side', models.CharField(choices=[('under', 'Under'), ('six', 'Six'), ('over', 'Over')], max_length=8)),
                ('won', models.BooleanField(default=False)),
                ('payout', models.PositiveIntegerField(default=0)),
                ('bankroll_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.gamesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
