# Generated by Django 4.2.7 on 2025-11-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='dice_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='dice_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='dice_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='dice_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='dice_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='dice_6',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
