# Generated by Django 4.2.7 on 2025-12-07 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_gameround_dice_1_gameround_dice_2_gameround_dice_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_dashboard', models.BooleanField(default=True)),
                ('can_view_game_ui', models.BooleanField(default=True)),
                ('can_control_dice', models.BooleanField(default=True)),
                ('can_view_recent_rounds', models.BooleanField(default=True)),
                ('can_view_all_bets', models.BooleanField(default=True)),
                ('can_view_wallets', models.BooleanField(default=True)),
                ('can_view_workers', models.BooleanField(default=True)),
                ('can_view_deposit_requests', models.BooleanField(default=True)),
                ('can_view_transactions', models.BooleanField(default=True)),
                ('can_view_game_settings', models.BooleanField(default=False)),
                ('can_view_admin_management', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
