# Generated by Django 4.2.7 on 2025-12-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_adminpermissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpermissions',
            old_name='can_view_workers',
            new_name='can_view_players',
        ),
    ]
