# Generated by Django 4.2.7 on 2026-01-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_workers_to_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpermissions',
            name='can_view_game_ui',
        ),
    ]
