# Generated by Django 4.2.7 on 2026-01-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_ui_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='betting_close_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='gameround',
            name='dice_result_seconds',
            field=models.IntegerField(default=51),
        ),
        migrations.AddField(
            model_name='gameround',
            name='dice_roll_seconds',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='gameround',
            name='round_end_seconds',
            field=models.IntegerField(default=70),
        ),
    ]
