# Generated by Django 4.2.7 on 2026-01-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_add_round_timing_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissions',
            name='can_view_withdraw_requests',
            field=models.BooleanField(default=True),
        ),
    ]
