# Generated by Django 4.2.7 on 2026-01-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_diceresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissions',
            name='can_manage_payment_methods',
            field=models.BooleanField(default=True),
        ),
    ]
