# Generated by Django 4.2.7 on 2026-04-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_colour_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketbet',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cricketbet',
            name='potential_payout',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cricketbet',
            name='stake',
            field=models.DecimalField(decimal_places=2, help_text='Stake in rupees', max_digits=12),
        ),
    ]
