# Generated by Django 4.2.7 on 2026-07-27 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0029_trading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenRoad2Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('hardcore', 'Hardcore')], max_length=16)),
                ('bet', models.PositiveIntegerField()),
                ('step', models.PositiveIntegerField(default=0)),
                ('crash_at', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cashed_out', 'Cashed out'), ('crashed', 'Crashed'), ('completed', 'Completed')], db_index=True, default='active', max_length=16)),
                ('payout', models.PositiveIntegerField(default=0)),
                ('server_seed', models.CharField(max_length=64)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('client_seed', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChickenRoadRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('hardcore', 'Hardcore')], max_length=16)),
                ('bet', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('cashed_out', 'Cashed Out'), ('burned', 'Burned'), ('won', 'Won')], db_index=True, default='playing', max_length=16)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('road_secret', models.JSONField(default=list)),
                ('payout', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='cricketoutcomeresult',
            new_name='game_cricke_event_i_0e2430_idx',
            old_name='game_cricke_event_i_7d0f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='cricketoutcomeresult',
            new_name='game_cricke_is_fina_3d88ef_idx',
            old_name='game_cricke_is_fina_2a8c11_idx',
        ),
        migrations.AddField(
            model_name='chickenroadround',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chicken_road_rounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chickenroad2round',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chicken_road2_rounds', to=settings.AUTH_USER_MODEL),
        ),
    ]
