# Generated by Django 4.2.7 on 2026-08-05 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0031_vortex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('chat_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('last_alert_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
