# Generated by Django 6.1 on 2026-08-15 17:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('flying', 'Flying'), ('crashed', 'Crashed')], default='waiting', max_length=16)),
                ('crash_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seed', models.CharField(default='', max_length=64)),
                ('wait_ms', models.PositiveIntegerField(default=5000)),
                ('growth', models.FloatField(default=0.058)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('crashed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cashed', 'Cashed'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('cashout_mult', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('win', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auto_cashout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.gameround')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['player', 'round', 'panel'], name='jet_bet_player_panel_idx')],
            },
        ),
    ]
