# Generated by Django 6.1 on 2026-08-09 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selected', models.JSONField(default=list)),
                ('multipliers', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('selecting', 'Selecting'), ('settled', 'Settled')], default='selecting', max_length=16)),
                ('total_multiplier', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='boxes.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
