# Generated by Django 5.1.15 on 2026-09-03 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('feature_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.CharField(db_index=True, max_length=64)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=14)),
                ('used_free_spin', models.BooleanField(default=False)),
                ('grid_json', models.TextField()),
                ('result_json', models.TextField()),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('free_spins_after', models.IntegerField(default=0)),
                ('pearls_after', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
