# Generated by Django 6.1 on 2026-08-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.DecimalField(decimal_places=2, max_digits=12)),
                ('crash_at', models.FloatField()),
                ('pumps', models.PositiveIntegerField(default=0)),
                ('multiplier', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('cashed', 'Cashed out'), ('crashed', 'Crashed')], default='playing', max_length=16)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
