# Generated by Django 5.2.16 on 2026-07-27 17:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('hardcore', 'Hardcore')], max_length=16)),
                ('bet', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('cashed_out', 'Cashed Out'), ('burned', 'Burned'), ('won', 'Won')], default='playing', max_length=16)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('road_secret', models.JSONField(default=list)),
                ('payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
