# Generated by Django 6.0.7 on 2026-07-25 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('betting', 'Betting'), ('trading', 'Trading'), ('settled', 'Settled')], default='betting', max_length=10)),
                ('final_pct', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('phase_ends_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('up_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('down_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('up_players', models.IntegerField(default=0)),
                ('down_players', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('bet', 'Bet placed'), ('win', 'Win payout'), ('loss', 'Loss'), ('cashout', 'Cash out'), ('refund', 'Refund')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('up', 'UP'), ('down', 'DOWN')], max_length=4)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('won', models.BooleanField(blank=True, null=True)),
                ('cashed_out', models.BooleanField(default=False)),
                ('cashout_pct', models.FloatField(blank=True, null=True)),
                ('cashout_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.round')),
            ],
            options={
                'unique_together': {('user', 'round')},
            },
        ),
    ]
