# Generated by Django 5.2.16 on 2026-07-27 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=1000000, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('hardcore', 'Hardcore')], max_length=16)),
                ('bet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('step', models.PositiveIntegerField(default=0)),
                ('crash_at', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cashed_out', 'Cashed out'), ('crashed', 'Crashed'), ('completed', 'Completed')], db_index=True, default='active', max_length=16)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('server_seed', models.CharField(max_length=64)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('client_seed', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('bet', 'Bet'), ('win', 'Win'), ('reset', 'Reset'), ('loss', 'Loss')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='game.player')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='game.round')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
