# Generated by Django 5.2.17 on 2026-08-15 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bankroll', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('ante', models.PositiveIntegerField()),
                ('play_chip', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(blank=True, choices=[('', 'None'), ('play', 'Play'), ('fold', 'Fold')], default='', max_length=8)),
                ('p1_label', models.CharField(max_length=2)),
                ('p1_value', models.PositiveSmallIntegerField()),
                ('p1_symbol', models.CharField(max_length=2)),
                ('p1_red', models.BooleanField(default=False)),
                ('p2_label', models.CharField(max_length=2)),
                ('p2_value', models.PositiveSmallIntegerField()),
                ('p2_symbol', models.CharField(max_length=2)),
                ('p2_red', models.BooleanField(default=False)),
                ('p3_label', models.CharField(max_length=2)),
                ('p3_value', models.PositiveSmallIntegerField()),
                ('p3_symbol', models.CharField(max_length=2)),
                ('p3_red', models.BooleanField(default=False)),
                ('d1_label', models.CharField(max_length=2)),
                ('d1_value', models.PositiveSmallIntegerField()),
                ('d1_symbol', models.CharField(max_length=2)),
                ('d1_red', models.BooleanField(default=False)),
                ('d2_label', models.CharField(max_length=2)),
                ('d2_value', models.PositiveSmallIntegerField()),
                ('d2_symbol', models.CharField(max_length=2)),
                ('d2_red', models.BooleanField(default=False)),
                ('d3_label', models.CharField(max_length=2)),
                ('d3_value', models.PositiveSmallIntegerField()),
                ('d3_symbol', models.CharField(max_length=2)),
                ('d3_red', models.BooleanField(default=False)),
                ('player_hand', models.CharField(blank=True, default='', max_length=20)),
                ('dealer_hand', models.CharField(blank=True, default='', max_length=20)),
                ('dealer_qualified', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('', 'None'), ('fold', 'Fold'), ('dealer_nq', 'Dealer not qualified'), ('player_win', 'Player win'), ('dealer_win', 'Dealer win'), ('tie', 'Tie')], default='', max_length=12)),
                ('won', models.BooleanField(default=False)),
                ('payout', models.PositiveIntegerField(default=0)),
                ('bankroll_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.gamesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
